pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Build') {
            steps {
                echo 'build project'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy the project'
            }
        }
    }
}
